apiVersion: v1
kind: Pod
metadata:
  name: mosquitto
  labels:
    srvc: mqtt-broker
spec:
  containers:
    - name: mosquitto
      image: localhost:5000/mosquitto
      ports:
        - containerPort: 1883