apiVersion: v1
kind: Pod
metadata:
  name: mqtt-consumer
  labels:
    app: java-stateless-v.01
spec:
  containers:
    - name: mqtt-consumer
      image: localhost:5000/mqtt-consumer
      ports:
        - containerPort: 8080
